version: 2
jobs:
  build:
    docker:
     - image: circleci/python:3.7.3
    working_directory: ~/app

    steps:
      - checkout
      
      - run:
        pip install tox codecov

      - run:
          name: run tests
          command: |
            tox
      - run:
          name: Update coverage
          command: |
            codecov
          when: on_success

      - store_artifacts:
          path: .coverage