name: Build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-:
    - name: Run Tests dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - uses: actions/cache@v1
      with:
        path: .tox
        key: ${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-tox-:
    - name: Run Tests
      run: |
        tox -e=py39
